In [2]:
import cv2
import numpy as np

In [7]:
img=cv2.imread("img2.jpg") #image read
re_img=cv2.resize(img,(700,300))
cv2.imshow("TomJerry",re_img) #image show
cv2.waitKey(0)  #image frame wait -ms and 0 pass keyboard any key pres
cv2.destroyAllWindows() #closes all the windows

In [27]:
img=cv2.imread("img2.jpg") #image read
print(img)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [4]:
v=np.array([1,2,3,1,2,3])
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
img=cv2.imread("img2.jpg")
re_img=cv2.resize(img,(300,200))
#h=np.vstack((re_img,re_img))   #it is arranged in vertical use v
h=np.hstack((re_img,re_img))   #it is arranged in horizantally use h
cv2.imshow("Doremon",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
img=cv2.imread("img2.jpg")
re_img=cv2.resize(img,(300,200))
h=np.hstack((re_img,re_img))   #it is arranged in horizantally use v  here we can increase the no we want to dispay by adding re_img
v=np.vstack((h,h))   #now here it displays the two horizantal way in vertical way and displays 4 images
cv2.imshow("Doremon",v)
cv2.waitKey(0)
cv2.destroyAllWindows()